name: tfcbm
version: '1.1.5'
summary: The Friendly Clipboard Manager
description: |
  Track clipboard history with support for text, images, and files.
  Search, tag, and organize clipboard items with keyboard shortcuts.
contact: https://github.com/dyslechtchitect/tfcbm/issues
donation: https://github.com/dyslechtchitect/tfcbm#support-this-project
license: GPL-3.0-or-later
grade: stable
confinement: strict
base: core24

adopt-info: tfcbm

apps:
  tfcbm:
    extensions: [gnome]
    command: usr/bin/tfcbm
    desktop: usr/share/applications/io.github.dyslechtchitect.tfcbm.desktop
    common-id: io.github.dyslechtchitect.tfcbm
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - gsettings
      - unity7

parts:
  tfcbm:
    source: .
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    build-packages:
      - python3-dev
    stage-packages:
      - python3
      - python3-gi
      - xdotool
      - dconf-cli
      - libproxy1v5
    parse-info:
      - usr/share/metainfo/io.github.dyslechtchitect.tfcbm.metainfo.xml
